[package]
name = "minilake-cli"
description = "MiniLake command line interface"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[[bin]]
name = "minilake"
path = "src/main.rs"

[dependencies]
minilake-core.workspace = true
minilake-storage.workspace = true
minilake-exec.workspace = true
minilake-sql.workspace = true
clap.workspace = true
anyhow.workspace = true
